run:
  timeout: 3m
linters:
  disable-all: true
  enable:
    - dogsled
    - dupl
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  fast: false
linters-settings:
  misspell:
    locale: US
